### ISSUE TITLE
Error when trying to generate code

### ISSUE THREAD

**Issue by gdethier** [pousse-cafe/pousse-cafe-eclipse-plugin#18]
The following stack trace is displayed when trying to trigger code generation in a project.

Unsuccessful workarounds:
- closing/re-opening the project
- restarting workspace

```
Caused by: java.lang.NullPointerException
	at poussecafe.eclipse.plugin.core.PousseCafeProject.getSourceFolder(PousseCafeProject.java:162)
	at poussecafe.eclipse.plugin.handlers.GenerateCodeHandler.updateCode(GenerateCodeHandler.java:92)
	at poussecafe.eclipse.plugin.handlers.GenerateCodeHandler.generateCode(GenerateCodeHandler.java:74)
	at poussecafe.eclipse.plugin.handlers.GenerateCodeHandler.tryGenerateCode(GenerateCodeHandler.java:62)
	at poussecafe.eclipse.plugin.handlers.GenerateCodeHandler.execute(GenerateCodeHandler.java:41)
	at org.eclipse.ui.internal.handlers.HandlerProxy.execute(HandlerProxy.java:283)
	at org.eclipse.ui.internal.handlers.E4HandlerProxy.execute(E4HandlerProxy.java:97)
	at jdk.internal.reflect.GeneratedMethodAccessor159.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.eclipse.e4.core.internal.di.MethodRequestor.execute(MethodRequestor.java:58)
	... 37 more
```

**Comment by gdethier** [comment]
The solution to this bug is probably linked to [this](https://stackoverflow.com/a/20494107/2703552).
