### ISSUE TITLE
Duplicate markers appear on wrong lines

### ISSUE THREAD

**Issue by gdethier** [pousse-cafe/pousse-cafe-eclipse-plugin#19]
While creating a new container aggregate, markers are getting duplicated and associated with wrong lines in the file.

Cleaning the project solves the issue so this seems to be linked to incremental build.

Also, deleting the markers manually then triggering an incremental build recreates all markers (i.e. the expected ones plus duplicates) so this hints for model state issue.

The following (edited) error can be seen in the log just before the above situation occurs.

```
poussecafe.source.analysis.ResolutionException: Unable to load class XXX
	at poussecafe.source.analysis.CompilationUnitResolver.newResolutionException(CompilationUnitResolver.java:61)
	at poussecafe.source.analysis.CompilationUnitResolver.lambda$resolve$4(CompilationUnitResolver.java:152)
	at java.base/java.util.Optional.orElseThrow(Optional.java:408)
	at poussecafe.source.analysis.CompilationUnitResolver.resolve(CompilationUnitResolver.java:152)
	at poussecafe.source.analysis.TypeDeclarationResolver.resolve(TypeDeclarationResolver.java:17)
	at poussecafe.source.analysis.TypeDeclarationResolver.resolve(TypeDeclarationResolver.java:17)
	at poussecafe.source.analysis.ResolvedExpression.typeName(ResolvedExpression.java:41)
	at poussecafe.source.analysis.ResolvedExpression.asType(ResolvedExpression.java:53)
	at poussecafe.source.analysis.ProducedEventAnnotation.<init>(ProducedEventAnnotation.java:11)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1655)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578)
	at poussecafe.source.analysis.MessageListenerMethod.producedEvents(MessageListenerMethod.java:51)
	at poussecafe.source.model.MessageListener$Builder.withMethodDeclaration(MessageListener.java:133)
	at poussecafe.source.analysis.SourceModelBuilderVisitor.visit(SourceModelBuilderVisitor.java:234)
	at poussecafe.source.analysis.TypeResolvingCompilationUnitVisitor$1.visit(TypeResolvingCompilationUnitVisitor.java:138)
	at org.eclipse.jdt.core.dom.MethodDeclaration.accept0(MethodDeclaration.java:674)
	at org.eclipse.jdt.core.dom.ASTNode.accept(ASTNode.java:3012)
	at org.eclipse.jdt.core.dom.ASTNode.acceptChildren(ASTNode.java:3083)
	at org.eclipse.jdt.core.dom.TypeDeclaration.accept0(TypeDeclaration.java:526)
	at org.eclipse.jdt.core.dom.ASTNode.accept(ASTNode.java:3012)
	at org.eclipse.jdt.core.dom.ASTNode.acceptChildren(ASTNode.java:3083)
	at org.eclipse.jdt.core.dom.TypeDeclaration.accept0(TypeDeclaration.java:526)
	at org.eclipse.jdt.core.dom.ASTNode.accept(ASTNode.java:3012)
	at org.eclipse.jdt.core.dom.ASTNode.acceptChildren(ASTNode.java:3083)
	at org.eclipse.jdt.core.dom.CompilationUnit.accept0(CompilationUnit.java:258)
	at org.eclipse.jdt.core.dom.ASTNode.accept(ASTNode.java:3012)
	at poussecafe.source.analysis.TypeResolvingCompilationUnitVisitor.visit(TypeResolvingCompilationUnitVisitor.java:31)
	at poussecafe.source.SourceScanner.includeSource(SourceScanner.java:40)
	at poussecafe.eclipse.plugin.builder.PousseCafeBuilder.includeFile(PousseCafeBuilder.java:245)
	at poussecafe.eclipse.plugin.builder.PousseCafeBuilder.incrementalBuild(PousseCafeBuilder.java:164)
	at poussecafe.eclipse.plugin.builder.PousseCafeBuilder.build(PousseCafeBuilder.java:75)
	at org.eclipse.core.internal.events.BuildManager$2.run(BuildManager.java:845)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:228)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:276)
	at org.eclipse.core.internal.events.BuildManager$1.run(BuildManager.java:329)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:332)
	at org.eclipse.core.internal.events.BuildManager.basicBuildLoop(BuildManager.java:384)
	at org.eclipse.core.internal.events.BuildManager.build(BuildManager.java:405)
	at org.eclipse.core.internal.events.AutoBuildJob.doBuild(AutoBuildJob.java:154)
	at org.eclipse.core.internal.events.AutoBuildJob.run(AutoBuildJob.java:244)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
```

**Comment by gdethier** [comment]
Could not reproduce the issue with the latest release (0.4.1).
